export const COMMON_PROFESSIONS = [
  "Academic Researcher",
  "Accountant",
  "Actor",
  "Actress",
  "Agricultural Scientist",
  "AI Engineer",
  "Anthropologist",
  "Archaeologist",
  "Astronomer",
  "Attorney",
  "Auditor",
  "Author",
  "Baker",
  "Bartender",
  "Biologist",
  "Bus Driver",
  "Business Analyst",
  "Butcher",
  "Carpenter",
  "Chef",
  "Chemical Engineer",
  "Chemist",
  "Civil Engineer",
  "Cloud Architect",
  "Cook",
  "Customs Officer",
  "Cybersecurity Specialist",
  "Data Scientist",
  "Data Analyst",
  "Dental Hygienist",
  "Dentist",
  "Dietitian",
  "Diplomat",
  "Doctor",
  "Driver",
  "Economist",
  "Education Consultant",
  "Electrical Engineer",
  "Electrician",
  "Entrepreneur",
  "Environmental Scientist",
  "Event Planner",
  "Farmer",
  "Fashion Designer",
  "Film Director",
  "Financial Analyst",
  "Firefighter",
  "Fisheries Manager",
  "Flight Attendant",
  "Forestry Officer",
  "Geologist",
  "Government Officer",
  "Graphic Designer",
  "Horticulturist",
  "Hotel Manager",
  "Human Resources Manager",
  "Insurance Agent",
  "Interior Designer",
  "Investment Banker",
  "Journalist",
  "Judge",
  "Laboratory Technician",
  "Language Instructor",
  "Lawyer",
  "Lecturer",
  "Legal Advisor",
  "Librarian",
  "Machine Learning Engineer",
  "Marketing Manager",
  "Mason",
  "Mechanic",
  "Mechanical Engineer",
  "Midwife",
  "Military Officer",
  "Musician",
  "Network Engineer",
  "Nurse",
  "Nutritionist",
  "Ophthalmologist",
  "Optometrist",
  "Paralegal",
  "Paramedic",
  "Pediatrician",
  "Pharmacist",
  "Photographer",
  "Physicist",
  "Physiotherapist",
  "Pilot",
  "Plumber",
  "Police Officer",
  "Principal",
  "Procurement Specialist",
  "Product Manager",
  "Psychiatrist",
  "Psychologist",
  "QA Engineer",
  "Radiologist",
  "Research Scientist",
  "Restaurant Manager",
  "Robotics Engineer",
  "Sales Executive",
  "School Administrator",
  "School Teacher",
  "Singer",
  "Social Media Influencer",
  "Software Engineer",
  "Special Education Teacher",
  "Surgeon",
  "Tailor",
  "Tax Consultant",
  "Taxi Driver",
  "Therapist",
  "Tour Guide",
  "Travel Agent",
  "Truck Driver",
  "University Professor",
  "UX Designer",
  "Veterinary Doctor",
  "Videographer",
  "Web Developer",
  "Welder",
  "Wildlife Conservationist",
  "Writer",
  "AI Researcher",
];
