# Generated by Django 4.2.16 on 2026-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture_content_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
