# Generated by Django 4.2.16 on 2026-07-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_availability_report_blockeduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
