# Generated by Django 4.2.16 on 2026-07-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="website_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
